### ISSUE TITLE
Error "Could not setup wiki content" when creating a new demo

### ISSUE THREAD

**Issue by claudiomelo** [MatmaRex/patchdemo#471] opened 2022-07-07 17:22 UTC
Hello, I am getting this error, every time a try to create a new demo. 
Thanks in advance.

```
Converting djvu metadata...PHP Notice:  Undefined index: backend in /srv/patchdemo-wikis/10db4188e5/w/includes/filebackend/FileBackendGroup.php on line 112
Notice: Undefined index: backend in /srv/patchdemo-wikis/10db4188e5/w/includes/filebackend/FileBackendGroup.php on line 112
InvalidArgumentException from line 154 of /srv/patchdemo-wikis/10db4188e5/w/includes/filebackend/FileBackendGroup.php: Cannot register a backend with no name.
#0 /srv/patchdemo-wikis/10db4188e5/w/includes/filebackend/FileBackendGroup.php(141): FileBackendGroup->register(Array, false)
#1 /srv/patchdemo-wikis/10db4188e5/w/includes/ServiceWiring.php(653): FileBackendGroup->__construct(Object(MediaWiki\Config\ServiceOptions), Object(ConfiguredReadOnlyMode), Object(HashBagOStuff), Object(WANObjectCache), Object(MimeAnalyzer), Object(MediaWiki\FileBackend\LockManager\LockManagerGroupFactory), Object(MediaWiki\FileBackend\FSFile\TempFSFileFactory), Object(Wikimedia\ObjectFactory\ObjectFactory))
#2 /srv/patchdemo-wikis/10db4188e5/w/vendor/wikimedia/services/src/ServiceContainer.php(447): Wikimedia\Services\ServiceContainer::{closure}(Object(MediaWiki\MediaWikiServices))
#3 /srv/patchdemo-wikis/10db4188e5/w/vendor/wikimedia/services/src/ServiceContainer.php(416): Wikimedia\Services\ServiceContainer->createService('FileBackendGrou...')
#4 /srv/patchdemo-wikis/10db4188e5/w/includes/MediaWikiServices.php(298): Wikimedia\Services\ServiceContainer->getService('FileBackendGrou...')
#5 /srv/patchdemo-wikis/10db4188e5/w/includes/MediaWikiServices.php(988): MediaWiki\MediaWikiServices->getService('FileBackendGrou...')
#6 /srv/patchdemo-wikis/10db4188e5/w/includes/filerepo/FileRepo.php(186): MediaWiki\MediaWikiServices->getFileBackendGroup()
#7 /srv/patchdemo-wikis/10db4188e5/w/includes/filerepo/LocalRepo.php(77): FileRepo->__construct(Array)
#8 /srv/patchdemo-wikis/10db4188e5/w/includes/filerepo/RepoGroup.php(413): LocalRepo->__construct(Array)
#9 /srv/patchdemo-wikis/10db4188e5/w/includes/filerepo/RepoGroup.php(400): RepoGroup->newRepo(Array)
#10 /srv/patchdemo-wikis/10db4188e5/w/maintenance/refreshImageMetadata.php(284): RepoGroup->newCustomLocalRepo(Array)
#11 /srv/patchdemo-wikis/10db4188e5/w/maintenance/refreshImageMetadata.php(140): RefreshImageMetadata->newLocalRepo(true, false, false, false)
#12 /srv/patchdemo-wikis/10db4188e5/w/includes/installer/DatabaseUpdater.php(1184): RefreshImageMetadata->execute()
#13 /srv/patchdemo-wikis/10db4188e5/w/includes/installer/DatabaseUpdater.php(547): DatabaseUpdater->doConvertDjvuMetadata()
#14 /srv/patchdemo-wikis/10db4188e5/w/includes/installer/DatabaseUpdater.php(511): DatabaseUpdater->runUpdates(Array, false)
#15 /srv/patchdemo-wikis/10db4188e5/w/maintenance/update.php(193): DatabaseUpdater->doUpdates(Array)
#16 /srv/patchdemo-wikis/10db4188e5/w/maintenance/includes/MaintenanceRunner.php(309): UpdateMediaWiki->execute()
#17 /srv/patchdemo-wikis/10db4188e5/w/maintenance/doMaintenance.php(85): MediaWiki\Maintenance\MaintenanceRunner->run()
#18 /srv/patchdemo-wikis/10db4188e5/w/maintenance/update.php(264): require_once('/srv/patchdemo-...')
#19 {main}
PATCHDEMO='/var/www/html' WIKI='10db4188e5' /var/www/html/deletewiki.sh
+ rm -rf /var/www/html/wikis/10db4188e5
+ mysql -u patchdemo --password=patchdemo -e 'DROP DATABASE IF EXISTS patchdemo_10db4188e5'
Could not setup wiki content
```

**Comment by MatmaRex** [comment] 2022-07-07 21:41
This seems to be caused by QuickInstantCommons together with the patch https://gerrit.wikimedia.org/r/c/mediawiki/core/+/785387. I filed https://phabricator.wikimedia.org/T312598 about it.

Workaround for Patch Demo users:
* Either uncheck "Load images from Commons" when creating the new wiki
* Or include the revert patch https://gerrit.wikimedia.org/r/c/mediawiki/core/+/811964 in your demo

**Comment by edg2s** [comment] 2022-07-08 20:42
I've live-patched the form to default to InstantCommons:
```
diff --git a/index.php b/index.php
index 6eff008..59d6c2f 100644
--- a/index.php
+++ b/index.php
@@ -176,8 +176,9 @@ if ( !$canCreate ) {
                                                        'classes' => [ 'form-instantCommonsMethod' ],
                                                        'name' => 'instantCommonsMethod',
                                                        'options' => [
-                                                               [ 'data' => 'quick', 'label' => 'QuickInstantCommons' ],
+//                                                             [ 'data' => 'quick', 'label' => 'QuickInstantCommons' ],
                                                                [ 'data' => 'full', 'label' => 'InstantCommons' ],
+                                                               [ 'data' => 'quick', 'label' => 'QuickInstantCommons' ],
                                                        ]
                                                ] ),
                                                [
```

**Comment by MatmaRex** [comment] 2022-07-09 20:21
The underlying bug is fixed now thanks to @bawolff, see https://phabricator.wikimedia.org/T312598 for details.

I confirmed that it works on Patch Demo too and undid the live hack.

**Closed by MatmaRex** 2022-07-09 20:21 UTC
