### ISSUE TITLE
Uncaught Exception: It was attempted to load Parsoid twice

### ISSUE THREAD

**Issue by Funcer8** [MatmaRex/patchdemo#408] opened 2022-01-08 06:37 UTC
https://patchdemo.wmflabs.org/wikis/27170410ed/w/
I meet this error so I create the demo above without any change, it reproduced.

**Comment by edg2s** [comment] 2022-01-09 01:01
Can you let us know which patches and other options you were using so we can try to reproduce this error?

**Comment by Funcer8** [comment] 2022-01-09 04:41
Oh, The link attached is wrong, edited...
I mean leave all options as default (Wikimedia preset), no patch applied.
It worked fine on at least Dec 14, 2021. I created a usable demo based on Wikimedia preset that day.

**Comment by edg2s** [comment] 2022-01-09 11:49
There have been no changes to Patch Demo since that date, so this must be an upstream issue, probably with Parsoid? cc @cscott

**Comment by edg2s** [comment] 2022-01-10 15:22
It looks like the error is coming from GrowthExperiments which loads Parsoid directly as some sort of testing hack:

https://gerrit.wikimedia.org/r/c/mediawiki/extensions/GrowthExperiments/+/699705/23/tests/selenium/fixtures/GrowthExperiments.LocalSettings.php

I'm going to temporarily remove GrowthExperiments from the Wikimedia default until this is resolved.

cc @kostajh

**Comment by edg2s** [comment] 2022-01-10 15:32
I created a wiki with this patch and it is still broken. Patch Demo installs parsoid in `$IP/parsoid`, not `$IP/services/parsoid`. Maybe you can query the extension registry and look for something with `/parsoid`?

**Comment by edg2s** [comment] 2022-01-10 15:35
Also you should always use `$wgExtensionDirectory` instead of `$IP/extensions`.

**Comment by kostajh** [comment] 2022-01-10 17:32
Should actually be fixed by https://gerrit.wikimedia.org/r/c/mediawiki/extensions/GrowthExperiments/+/752711

**Comment by MatmaRex** [comment] 2022-01-11 15:24
Fixed indeed, thanks all.

**Closed by MatmaRex** 2022-01-11 15:24 UTC
